#https://docs.docker.com/engine/reference/builder/
#FROM debian:8
#CMD ["echo", "hello world"]

#nginx with custom index.html
#FROM nginx:1.15
#COPY index.html /usr/share/nginx/html
#EXPOSE 80
#docker build -t webserver .
#docker run --rm -it -p 8082:80 webserver