###
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "number": "12345",
  "name": "test1"
}

###
GET http://localhost:8080/contacts/2

###
GET http://localhost:8080/contacts/search/findByName?name=test

