version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students

  migration:
    image: liquibase/liquibase:4.26-alpine
    container_name: liquibase
    depends_on:
      - db
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/students
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources/liquibase/:/liquibase/changelog/
